version: "3.9"

services:
  db:
    image: mysql:8.0.36
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 30102002
      MYSQL_DATABASE: books
      MYSQL_PASSWORD: 30102002


  bookstore:
    image: yonklongschlong/bookstore:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/books
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 30102002
    depends_on:
      - db


